### ISSUE TITLE
Refactoring branding

### ISSUE THREAD

**Issue by 5h0bh4nk** [5h0bh4nk/SHUBH_TEAMS_#5]
This project was made as a part of Microsoft engage program , so it specifies Microsoft teams clone . So , the branding needs to be changed , i.e , the logo and name must be changed everywhere in the project .

**Comment by koushikpuppala** [comment]
I can work on this If you want @5h0bh4nk

**Comment by 5h0bh4nk** [comment]
Sure @koushikpuppala

**Comment by koushikpuppala** [comment]
thanks

**Comment by koushikpuppala** [comment]
@5h0bh4nk Can I have the Logo and name of the app

**Comment by 5h0bh4nk** [comment]
You cam suggest any name if u have

**Comment by 5h0bh4nk** [comment]
It needs a thought otherwise

**Comment by koushikpuppala** [comment]
I kept `Shubh Team` as name and now what is logo should I make it

**Comment by 5h0bh4nk** [comment]
Keep a random logo inage as of now

**Comment by koushikpuppala** [comment]
ok Then I will make one with canvas with app name

**Comment by koushikpuppala** [comment]
and I am making fixing few errors in code

**Comment by koushikpuppala** [comment]
![smart TEAM](https://user-images.githubusercontent.com/70138027/135647511-2f23ec63-d0f5-4ba9-9383-b153e2cfdc1e.png)

**Comment by 5h0bh4nk** [comment]
Looks good

**Comment by koushikpuppala** [comment]
ok
