### ISSUE TITLE
Folder structure change in documentation 

### ISSUE THREAD

**Issue by 5h0bh4nk** [5h0bh4nk/SHUBH_TEAMS_#6]
The Files have been restructured . So , it needs to be updated in the documentation . It can be done using a npm module .

**Comment by TheCodinggDude** [comment]
Hey @5h0bh4nk Can I work on this issue ?

**Comment by 5h0bh4nk** [comment]
Yes sure

**Comment by 5h0bh4nk** [comment]
Assigned to @TheCodinggDude
